server:
  port: 8080

spring:
  application:
    name: event-manager-ms
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/event-manager-ms}
      database: event-manager-ms
      auto-index-creation: true
  profiles:
    active: dev


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
jwt:
  secret: suaChaveSecretaMuitoLongaEAleatoriaAqui123456789
  expiration: 86400000

logging:
  level:
    root: INFO
    com.eventmanager: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
